name: Test and Build backend app

defaults:
  run:
    working-directory: "Back-end"

on:
  workflow_dispatch:
  push:
    branches:
    - Back-end
    paths:
    - 'Back-end/**'

jobs:
  TestAndBuild:
    name: Test
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Install and Test
      run: |
        apt-get update && apt-get -y install maven
        mvn clean test
    - name: Build java
      run: |
        mvn clean package
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.MY_TOKEN }}
    
    - name: Build and push image
      run: |
        docker build -t ghcr.io/ThiagoKinjo/backend-app:latest .
        docker push ghcr.io/ThiagoKinjo/backend-app:latest
