name: Build frontend app and deploy

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  BuildAndDeploy:
    name: Build frontend app and deploy
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get update && apt-get -y install npm
          npm install -g @angular/cli

      - name: Build Docker image
        run: |
          docker build -t frontend .

      - name: Test
        run: ng test

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ThiagoKinjo
          password: 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

      - name: Push Docker image to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: docker.pkg.github.com/${{ github.repository }}/frontend:latest
