name: Build frontend app and deploy



on:
  workflow_dispatch:
  push:
    branches:
      - frontend
  push:
    branches:
      - frontend
    paths:
      - 'frontend/**'

jobs:
  BuildAndDeploy:
    name: Build frontend app and deploy
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get update && apt-get -y install npm
          npm install -g @angular/cli

      - name: Build Docker image
        run: |
          docker build -t frontend .

      - name: Test
        run: ng test
