name: Build frontend app and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - Front-end
#    paths:#
#      - 'frontend/**'#

jobs:
  BuildAndDeploy:
    name: Build frontend app and deploy
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install nodejs npm -y
      - name: Build Docker image
        run: |
          cd frontend
          npm install
          npm run build
          docker build -t frontend .
      - name: Test
        run: ng test
      - name: List files in directory
        run: ls
