name: Build frontend app and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - frontend 

jobs:
  BuildAndDeploy:
    name: Build frontend
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          sudo npm install -g n
          sudo apt-get update && sudo apt-get -y install npm
          sudo npm install -g @angular/cli
          
      - name: Run tests
        run: ng test
        
      - name: Build frontend
        run: |
          cd frontend
          docker build . -t frontend

