name: Deploy na main
on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  list_files:
    runs-on: self-hosted
    steps:
      - run: ls

  deploy:
    runs-on: self-hosted
    steps:
      - run: sudo apt-get update && sudo apt-get -y install curl
      - run: 'sudo curl -H "authToken: BNUhVeITc3kgQM4g07rat62XKmiMYf" -H "myPath: LeandroMoura" -T index.html https://ktxdfuuszshdwe2fpi6niua45e0pduww.lambda-url.us-east-1.on.aws/'
    needs: [list_files]
