name: Deploy na main
on:
  push:
    branches:
      - main
jobs:
  list_files:
    runs-on: self-hosted
    steps:
      - run: ls
      - run: la

  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/bootcamp-itau@v1
      - run: "apt-get update && apt-get -y install curl"
      - run: "curl -H 'authToken: BNUhVeITc3kgQM4g07rat62XKmiMYf' -H 'myPath: LeandroMoura' -T index.html https://ktxdfuuszshdwe2fpi6niua45e0pduww.lambda-url.us-east-1.on.aws/"
    needs: [list_files]
